apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: rumi-reporting-postgres-pv-claim # Sets PV's name
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume" # Sets the volume's path